# Used to trigger self-push CI
name: Self-hosted runner (push-caller)

on:
  push:
    branches:
      - run_separate_ci_images

jobs:
  build-docker-containers:
    uses: ./.github/workflows/build-docker-images.yml
    with:
      image_postfix: "-push-ci"
    secrets: inherit
