name: Self-hosted runner (past-ci-caller)

on:
  push:
    branches:
      - run_get_and_set_job_links_in_ci

jobs:
  run_past_ci_pytorch_1-11:
    name: PyTorch 1.11
    if: always()
    uses: ./.github/workflows/self-past.yml
    with:
      framework: pytorch
      version: "1.11"
    secrets: inherit

  run_past_ci_pytorch_1-10:
    name: PyTorch 1.10
    if: always()
    needs: [run_past_ci_pytorch_1-11]
    uses: ./.github/workflows/self-past.yml
    with:
      framework: pytorch
      version: "1.10"
    secrets: inherit

  run_past_ci_tensorflow_2-5:
    name: TensorFlow 2.5
    if: always()
    needs: [run_past_ci_pytorch_1-10]
    uses: ./.github/workflows/self-past.yml
    with:
      framework: tensorflow
      version: "2.5"
    secrets: inherit
