name: Self-hosted runner (scheduled)

on:
  push:
    branches:
      - reproduce-slack-api-issue

jobs:
  send_results:
    name: Send results to webhook
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Send message to Slack
        env:
          CI_SLACK_BOT_TOKEN: ${{ secrets.CI_SLACK_BOT_TOKEN }}
          CI_SLACK_REPORT_CHANNEL_ID: ${{ secrets.CI_SLACK_CHANNEL_DUMMY_TESTS }}
        run: |
          pip install slack_sdk==3.18.3
          python utils/notification_service.py
